### ISSUE TITLE
unexpected token: pipeline

### ISSUE THREAD

**Issue by sebarre-talend** [jenkinsci/JenkinsPipelineUnit#170] opened 2020-02-04 10:21 UTC
Hello,

I hava an issue i don't understand.

With this code :
```
class CheckParameterTest extends DeclarativePipelineTest {

    @Before
    void setUp() throws Exception {
        baseScriptRoot = 'test/pipelines'
        scriptExtension = 'jenkins'
        super.setUp()
    }


    @Test
    void should_execute_without_errors() throws Exception {
        def script = runScript("test/pipelines/checkParametersTest.jenkins")
        printCallStack()
        assertJobStatusSuccess()
    }
}
```

calling this jenkinsfile :
```
pipeline {
    agent none
    stages {
        stage('test') {
            steps {
                sh 'echo "hello"'
            }
        }
    }
}
```

I have this exception :
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/Users/sebarre/Documents/Projets/my-project/test/pipelines/checkParametersTest.jenkins: 3: unexpected token: pipeline @ line 3, column 1.
   pipeline {
   ^

1 error
```

This is basically the same example as the README. What i am missing ?

**Comment by stchar** [comment] 2020-02-05 17:49
@sebarre-talend, 
I'm not 100% sure, but I think you're trying to compile Jenkinsfile with pure groovy. Have you managed to run testcases for scripted pipelines? Please see to demos with examples of project structure, links are in the readme.

**Comment by stchar** [comment] 2020-02-11 12:31
I tried, but cannot reproduce your issue.  I'm closing it. Please reopen if you still have some issues.

* Project structure
```
├── Jenkinsfile
├── build.gradle
└── src
    └── test
        └── groovy
            └── TestCase.groovy

```

* build.gradle
```groovy
plugins {
  id "java"
  id "groovy"
}

repositories {
  maven { url 'https://repo.jenkins-ci.org/releases/' }
  jcenter()
  mavenLocal()
}

dependencies {
  testImplementation "junit:junit:4.12"
  testImplementation "com.lesfurets:jenkins-pipeline-unit:1.3"
}

test {
  testLogging {
    events "PASSED", "FAILED", "SKIPPED"
  }
}
```

* src/test/groovy/TestCase.grovy
```groovy
import com.lesfurets.jenkins.unit.declarative.DeclarativePipelineTest
import org.junit.Before
import org.junit.Test

class CheckParameterTest extends DeclarativePipelineTest {

    @Before
    void setUp() throws Exception {
        super.setUp()
    }

    @Test
    void should_execute_without_errors() throws Exception {
        def script = runScript("Jenkinsfile")
        printCallStack()
        assertJobStatusSuccess()
    }
}
```
* Jenkinsfile
```groovy
pipeline {
    agent none
    stages {
        stage('test') {
            steps {
                sh 'echo "hello"'
            }
        }
    }
}
```


* Run (gradle version 6.1.1)
```
$ gradle test 

> Task :test

CheckParameterTest > should_execute_without_errors PASSED

BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed
```

**Closed by stchar** 2020-02-11 12:31 UTC
