### ISSUE TITLE
Getting a stackoverflow error

### ISSUE THREAD

**Issue by dineshgioe** [jenkinsci/JenkinsPipelineUnit#123] opened 2018-10-22 10:13 UTC
I was trying to use this library to test my pipeline code. I have my pipelines defined in a share library and I am calling this library as a pipeline script. Following code is configured as a pipeline code in the jenkin jobs.

**@Library('commons@develop')
import test.builds.designapp.Facade

new Facade(this).createPipeline()**

Facade is a groovy class which contains the required pipeline code. I have tried to test this by copying the same above exact lines into a file and loading the file using loadScript method.

        library = library()
                    .name('commons')
                    .retriever(gitSource('giturl'))
                    .targetPath(commonsPath)
                    .defaultVersion("develop")
                    .allowOverride(true)
                    .implicit(false)
                    .build()
        helper.registerSharedLibrary(library)

    @Test
    void should_execute_on_master() throws Exception {
        try{
            runScript('Jenkinsfile')
        } catch (Exception e){
            println e.getLocalizedMessage()
        }
    }

But when I tried to run the tests I am getting the "java.lang.StackOverflowError" with out any trace. I have tried in multiple ways but end up with same error. I would like to know if this is a proper way of using the jenkinspipelineunit.

**Comment by stchar** [comment] 2019-03-15 12:49
Hi, sorry, It's not clear what is wrong with it.  
If it is still actual, could you please submit a `testcase` to reproduce the issue?

**Comment by linehammer** [comment] 2019-12-09 04:32
A StackOverflowError is simply signals that there is no more memory available. It is to the stack what an OutOfMemoryError is to the heap: it simply signals that there is no more memory available. JVM has a given memory allocated for each stack of each thread, and if an attempt to call a method happens to fill this memory, JVM throws an error. Just like it would do if you were trying to write at index N of an array of length N. No memory corruption can happen. The stack can not write into the heap.

The common cause for a [stackoverflow](http://net-informations.com/java/cjava/stackoverflow.htm) is a bad recursive call. Typically, this is caused when your recursive functions doesn't have the correct termination condition, so it ends up calling itself forever. Or when the termination condition is fine, it can be caused by requiring too many recursive calls before fulfilling it.

Here's an example:

```
public class Overflow {
    public static final void main(String[] args) {
        main(args);
    }
}
```
That function calls itself repeatedly with no termination condition. Consequently, the stack fills up because each call has to push a return address on the stack, but the return addresses are never popped off the stack because the function never returns, it just keeps calling itself.

**Comment by axieum** [comment] 2024-07-16 14:00
This happens to be related to #585

**Comment by nre-ableton** [comment] 2024-07-30 19:26
I think @axieum is right, let's close this issue in favor of #585, since that one has more detail.

**Closed by nre-ableton** 2024-07-30 19:26 UTC
