### ISSUE TITLE
Add to array groovy operator (<<) MethodNotFound

### ISSUE THREAD

**Issue by mathieudevos** [jenkinsci/JenkinsPipelineUnit#253] opened 2020-07-24 13:42 UTC
Hey,

Back again with another issue. I have a rather simple groovy shared library that contains a pretty straightforward operation of the following:

```groovy
String[] commands = 'echo'
commands << '"hello world"'
commands << '|'
commands << 'grep hello'
sh commands.join(' ')
```

Now trying to run this with the test gives me the following error: 
`groovy.lang.MissingMethodException: No signature of method: [Ljava.lang.String;.leftShift() is applicable for argument types: (String) values: ["hello world"]`

Any idea how to get this one to resolve? I've attempted items such as: `helper.registerAllowedMethod('Ljava.lang.String;.leftShift()', ...)` and other things such as trying to register `<<` as an allowed method, but alas: same issue persists.

Any help with this would be much appreciated

**Comment by stchar** [comment] 2020-07-27 08:41
Hi @mathieudevos, what is your groovy version?

**Comment by stchar** [comment] 2020-08-07 10:02
Tried to reproduce it in pure groovy. Looks like your syntax is incorrect.
```
$> groovy --version
Groovy Version: 3.0.3 JVM: 13.0.2 Vendor: Oracle Corporation OS: Mac OS X

$> cat test.groovy 
String[] cmd = "echo"
    cmd << "Hello world"
    println cmd.join()

$> groovy test.groovy 
Caught: groovy.lang.MissingMethodException: No signature of method: [Ljava.lang.String;.leftShift() is applicable for argument types: (String) values: [Hello world]
groovy.lang.MissingMethodException: No signature of method: [Ljava.lang.String;.leftShift() is applicable for argument types: (String) values: [Hello world]
	at test.run(test.groovy:2)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by stchar** [comment] 2020-08-07 10:04
I've got it worked with following syntax
```
$> cat test.groovy 
def cmd = ["echo"]
    cmd << "Hello world"
    println cmd.join()

$> groovy test.groovy 
echoHello world
```

**Comment by stchar** [comment] 2020-08-07 10:06
I'm closing the issue. Please let me know if you need any further assist

**Closed by stchar** 2020-08-07 10:06 UTC
Labels: invalid
