### ISSUE TITLE
Custom method added with registerAllowedMethod is not being utilized.

### ISSUE THREAD

**Issue by MOB3BP** [jenkinsci/JenkinsPipelineUnit#623] opened 2023-08-23 13:16 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Testing environment is:
  intellij, gradle, groovy 3.0.11, java 11 sdk, junit-bom:5.9.1, spock-core:2.4-M1-groovy-3.0, jenkins-pipeline-unit:1.19
  ```
  ```text
groovy shared libraries are located in the ./vars folder
  ```

```text
The function I want to mock would be the mountWorkspaceOnODrive function what is located in the executeMake library inside the vars folder.
I tried multiple ways to add it, like:
helper.registerAllowedMethod('executeMake.mountWorkspaceOnODrive', [], {}), helper.registerAllowedMethod("mountWorkspaceOnODrive", [], {return 0}),  helper.registerAllowedMethod("executeMake", [], {})
none of them worked, the test every time tried to call the "real" function instead of recognizing that it is "mocked".
```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

I am not aware of the Jenkins master, agents are windows systems, but this is not ran on an agent, rather in a local IntelliJ environment in test form.

### Reproduction steps

Step 1: Created a test class extending the BasePipepleinTest class
Step 2: Created a setup method loading in the groovy shared library
Step 3: In the setUp function called the helpers registerAllowedMethod with the custom function I would like to mock
Step 4: Created a test method and called the function I would like to test (which has a call inside it for the custom function I added to the registerAllowedMethod )

### Expected Results

The expected result would be for the test to be successful, and the mock function call to produce the given output.

### Actual Results

The added function call was not recognized, and the interpreter tried to call the declared function instead of the "mock", so the test failed, because the defined mountWorkspaceOnODrive has a bat call, which is not defined in our environment (since Jenkins does not need it). And it would not need to fail, because with a mock the groovy would not even know what is in the function.

### Anything else?

When trying to test our groovy shared libraries, after making successful tests with the addBatMock() function, for the functions using bat commands, mocking the already tested functions does not work. Tried adding the custom method multiple ways: none of them worked.

**Comment by stefan6419846** [comment] 2023-08-24 08:17
Could you please provide some code reproducing your issue?

**Comment by MOB3BP** [comment] 2023-09-14 09:41
Sure, so right now I have a class in src/groovy/ExampleClass.groovy: 
package groovy
class ExampleClass{
    String path

    ExecuteMake(String path= "Example/Path") {
        this.path= path
    }

    void mountOnWorkspace()
    {
        bat label:"Mount Workspace", script:"_mount_on.bat"
    }
}
And have a test class in tests/groovy/test_exampleClass.groovy:
import groovy.*
class test_exampleClassSpec extends BasePipelineTest{
    ExampleClass eClass
    @Override
    @Before
    void setUp() {
        eClass= new ExampleClass ()
        super.setUp()
        Assert.assertNotNull(eClass)
    }


    @Test
    void testMountWorkspace() {
        helper.addBatMock('_mount_on.bat', 'Mount Successful!', 0)
        eClass.mountOnWorkspace()
        assertJobStatusSuccess()
        printCallStack()
    }
}
And for this I get: "No signature method groovy.ExampleClass.bat() is applivable for... error.
I even tried to use the "helper.registerAllowedMethod('groovy.ExampleClass.bat()', [LinkedHashMap]) {print('Mounted!')}", or "helper.registerAllowedMethod('mountOnWorkspace.bat', [LinkedHashMap]) {print('Mounted!')}", but got the same result.

**Comment by stefan6419846** [comment] 2023-09-14 09:48
You are passing a map to the script, so using something like

```groovy
helper.registerAllowedMethod('bat', [Map]) { args ->
    assert args == [label: 'Mount Workspace', script: '_mount_on.bat']
    return [stdout: 'Mount Successful!', exitValue: 0]
}
```

should work. (I have not tested it for your specific use case, but this is what works for me with `sh` calls which should be equivalent.)

**Comment by MOB3BP** [comment] 2023-09-14 11:41
I have tried it, but it still gives the same error: "groovy.lang.MissingMethodException: No signature of method: groovy.ExampleClass.bat() is applicable for argument types: (LinkedHashMap) values: [[label:Mount Workspace, script:_mount_on.bat]]
Possible solutions: wait(), wait(long), tap(groovy.lang.Closure), any(), wait(long, int), is(java.lang.Object)
I also tried switching the bat() to groovy.ExampleClass.bat()

**Comment by nre-ableton** [comment] 2023-09-14 11:58
If `ExampleClass` is going to be a standalone class (and not run directly as a `Jenkinsfile`), then it needs a script context. Please refer to the example in the project documentation here:

**Comment by MOB3BP** [comment] 2023-09-15 12:38
Okay I made the changes suggested: 
The test file test/groovy/ExampleClassSpec.groovy:
class ExampleClassSpec extends BasePipelineTest{
    ExampleClass exampleClass
    Object script
    @Override
    @Before
    void setUp() {
        super.setUp()
        this.script = loadScript('vars/testVar.groovy')
        exampleClass=  new ExecuteClass(script: script)
        Assert.assertNotNull(exampleClass)
        helper.addBatMock('_mount_on.bat', 'Mount Successful!', 0)
    }

    @Test
    void testMount() {
        exampleClass.mountWorkspaceOn()
        assertJobStatusSuccess()
        printCallStack()
    }
}
The class file src/groovy/ExampleClass.groovy:
package groovy

class ExampleClass implements Serializable {
    Object script

    ExecuteMake(Object script) {
        this.script = script
    }

    void mountWorkspaceOn()
    {
        bat label:"Mount Workspace", script:"_mount_on.bat"
    }
}
And I created a lib vars/testVar.groovy:
import groovy.ExampleClass 

void mountWorkspaceOn()
{
    new ExampleClass (script: this).mountWorkspaceOn()
}

But I still get the following error:
groovy.lang.MissingMethodException: No signature of method: groovy.ExampleClass.bat() is applicable for argument types: (LinkedHashMap) values: [[label:Mount Workspace, script:_mount_on.bat]]
Possible solutions: wait(), wait(long), tap(groovy.lang.Closure), any(), wait(long, int), is(java.lang.Object)

Also I tried just testing it out in lib environment, so I have a separate library with the mountWorkspaceOn() function, and when I test that with the addBatMock function, it works. My question there is that, if I try to mock a separate custom function, lets say:
I have added the following functions:
def void executeMake(String makeCommand, String makeEnv_path)
{
   bat label:"Executing Target ${makeCommand}", script: """cd /d ${makeEnv_path}
   make ${makeCommand}"""
}

def void executeAll() 
{
   executeMake("all")
   executeMake("all_features")
   executeMake("parse_compilerlog")
}

If I run the executeAll() function, the CallStack gives back the following calls:
   executeMake.executeAll()
      executeMake.bat({label=Executing Target all, script=cd /d <path>
   make all})
      executeMake.bat({label=Executing Target all_features, script=cd /d <path>
   make all_features})
      executeMake.bat({label=Executing Target parse_compilerlog, script=cd /d <path>
   make parse_compilerlog})
What can I do if I do not want to create a separate batMock for each of the different calls, but rather just mock the executeMake() function call? Why is the executeMake() call missing from the call stack?

**Comment by nre-ableton** [comment] 2023-09-15 13:15
In `ExampleClass`, you need to call `script.bat`, not just `bat`.

**Comment by MOB3BP** [comment] 2023-09-15 13:54
Thank you, I missed that, for that I got the following error: 
```
groovy.lang.MissingMethodException: No signature of method: java.util.LinkedHashMap.bat() is applicable for argument types: (LinkedHashMap) values: [[label:Mount on O: folder on O: drive, script:_mount_on_O.bat]]
Possible solutions: wait(), wait(long), get(java.lang.Object), get(java.lang.Object), get(java.lang.Object), tap(groovy.lang.Closure)
```

**Comment by nre-ableton** [comment] 2023-09-18 10:28
Where are `executeMake` and `executeAll` exactly? This is really confusing.

**Comment by nre-ableton** [comment] 2023-09-18 15:08
So I tried adding this code to an existing pipeline library project that I have (just so that I didn't need to bother with gradle etc), and it works fine. I'm not exactly sure what your problem is, but I would encourage you to investigate the following:

- `package groovy` seems weird to me, and I wonder if that isn't confusing the Groovy interpreter somehow. Maybe try a `com.yourcompany.whatever` structure?
- What version of JUnit are you using? I'm using JUnit 5, which means that I am using `@BeforeEach` instead of `@Before`
- I would move the `helper.addBatMock('_mount_on.bat', 'Mount Successful!', 0)` out of the `setUp` method and into the test method. In practice, this shouldn't matter because the mock should be registered either way, but it probably makes more sense to have this mock in the unit test method for the thing it's actually testing.
- You mentioned IntelliJ. Can you debug through the test? Put breakpoints everywhere, make sure that objects such as `script` are sane. You should be able to inspect its value, like so:

![Screenshot from 2023-09-18 17-05-29](https://github.com/jenkinsci/JenkinsPipelineUnit/assets/16208985/e80f6d66-d34d-4ca9-9a9e-b2f4ac4ccc67)

Hope this helps.

**Comment by MOB3BP** [comment] 2023-09-19 09:40
Thank you for your help! I found out the issue, because of your debug tip.
If I printed out the class of the script in the setUp() or the testMount() functions for example, I got "class resources.EmptyPipeline", but in the ExecuteMake constructor I got "class java.util.LinkedHashMap", and in the debugger I found out that for some reason the EmptyPipeline there is the value inside the LinkedHashMap, so I changed my ExecuteMake constructor to this:
ExecuteMake(Object script) {
        this.script = script['script']
    }
and it works...

**Comment by nre-ableton** [comment] 2023-09-19 09:46
Glad to hear that you got it working! I'll go ahead and close this issue now.

**Closed by nre-ableton** 2023-09-19 09:46 UTC
